spring.application.name=retail-store

server.servlet.context-path=/retail-store

spring.datasource.url=jdbc:mysql://localhost:3306/retail_store?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=KirthySamayam@225

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jackson.deserialization.fail-on-unknown-properties=true

security.max-failed-attempts=3

#Logging
spring.security.debug=false
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=OFF
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=OFF
logging.level.org.springframework.security=WARN

logging.level.com.retailstore.cart=DEBUG
logging.level.com.retailstore.category=INFO
logging.level.com.retailstore.inventory=INFO
logging.level.com.retailstore.order=INFO
logging.level.com.retailstore.payment=INFO
logging.level.com.retailstore.product=DEBUG
logging.level.com.retailstore.security=WARN
logging.level.com.retailstore.user=INFO

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=bandlasiva9@gmail.com
spring.mail.password=ozkeqarmzxaqzqir
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

report.email.to=svbandla@gmail.com

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# File upload limits
batch.upload.dir=uploads/
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.servlet.multipart.file-size-threshold=1KB

app.base-url=http://localhost:8080/retail-store

# Run the schema file on startup
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema-mysql.sql

# Disable Spring Batch auto init (we handle it manually)
spring.batch.jdbc.initialize-schema=never